<a href="https://colab.research.google.com/github/IshantWadhwa4/Machine_Learning/blob/master/tensorFlow/tensorFlow_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [0]:
string = tf.Variable(["Helo Tim!"], tf.string)

In [19]:
string.shape

TensorShape([1])

In [18]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [0]:
rank2_tensor = tf.Variable([[["test", "ok"], ["test", "yes"],["test", "yes"]]], tf.string)

In [28]:
rank2_tensor.shape
# row and column

TensorShape([1, 3, 2])

In [29]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [0]:
tensr = tf.ones([1,2,3]) 

In [32]:
tensr

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [0]:
tensrReshape = tf.reshape(tensr,[1,3,2])

In [37]:
tensrReshape

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [0]:
rank2 = tf.Variable([[1,2,3],[4,5,6]],tf.int64)

In [39]:
tf.rank(rank2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [40]:
rank2.shape

TensorShape([2, 3])

In [41]:
tf.shape(rank2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [42]:
tf.reshape(rank2,[3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>